### ISSUE TITLE
Charts are broken after Viewport change in FF

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-board-demo#68] opened 2017-08-03 08:13 UTC
Change the viewport with less width.
Titles are not centered;
Some charts width is not recalculated

**Comment by web-padawan** [comment] 2020-05-19 17:11
Firefox no longer needs polyfills now, and I was not able to reproduce this issue. Closing.

**Closed as completed by web-padawan** 2020-05-19 17:11 UTC
